Module2 task1
htmlacademy-vue/1422707-pizza-1 pull request #2
Opened 2022-02-20 15:43 UTC by askomarov

#Я не смог реализовать/понять
- как связать отключение функции drag если ингредиента уже 3
- как менять кол-во в инпуте counter ингредиентов при переносе элемента на пиццу, при том что кол-во ингредиентов в пицце к заказу увеличивается..

2022-02-20 20:00 UTC, pisarevamarina requested changes
хорошая работа) ты разобрался с передачей данных используя пропсы и эмиты, научился декомпозировать компоненты! оставила комментарии по коду, которые помогут сделать работу масштабируемый и подготовить к дальнейшим модулям, а так же доделать недостающий функционал. если будут вопросы - на связи в телеграмме. удачи ;)

2022-02-20 20:00 UTC, pisarevamarina commented on src/frontend/src/components/VRadioButton.vue
> +  <input type="radio" @change="changeValue" :checked="checked" :value="value" />
я бы оставила v-on="$listeners", как предлагала на консультации. таким образом мы можем в будущем добавить любое нативное событие для инпута и не создавать методов с эмитами как ты ниже для @change сделал. в текущей реализации, если например, нам понадобится событие @input, то нам так же нужно будет писать метод с эмитом.

2022-02-20 20:00 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +            class="visually-hidden"
класс обычно пишут в самом конце проспав, перед событиями)

2022-02-20 20:00 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            <li
думаю все-таки стоит вынести один ингредиент в отдельную сущность, таким образом будет проще отслеживать состояние всех ингредиентов и одного. позже добавится еще  функционал  и компонент будет труднее читаться

2022-02-20 20:00 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              <AppDrag :transfer-data="item" :draggable="true">
для того чтобы запретить drag&drop при достижении максимального количества можно завести переменную в дате, например isDraggable  (:draggable="isDraggable")и поставить вотчер  на уже выбранное количество этого ингидиента, если оно превышает допустимое значение - задавать isDraggable false. и опять же это будет гораздо удобнее делать в отдельном компоненте. то же самое и с изменением значения в инпуте при переносе

2022-02-20 20:00 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +  computed: {},
не используется, лучше удалить

2022-02-20 20:00 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    },
предлагаю использовать здесь конструкцию switch-case

2022-02-20 20:00 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderSouceSelector.vue
> +      ></VRadioButton>
пустые теги делаем самозакрывающимися
 <VRadioButton  
        name="sauce"
         :value="item"
         :checked="item.name === selectedSouce.name"
         @changeItemValue="changeSouce"/>

2022-02-20 20:00 UTC, pisarevamarina commented on src/frontend/src/common/helpers.js
> +    foundation: "tomato",
структуру данных у заглушек  менять не нужно, позже ты подключишь апи и все сломается

2022-02-26 19:20 UTC, pisarevamarina requested changes
супер, функционал полностью отрабатывает, осталось только изменить логику добавления классовостью (оставила комментарий как это можно сделать)

2022-02-26 19:20 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +        :class="`pizza--foundation--${orderedPizza.dougth.foundation}-${orderedPizza.souce.classWord}`"
объемную логику динамических классов я бы предложила вынести в computed свойство

2022-02-26 19:20 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +          ></VRadioButton>
если тег не содержит ничего в себе - используем самозакрытие <VRadioButton/>

2022-02-26 19:20 UTC, pisarevamarina commented on src/frontend/src/common/helpers.js
> +    foundation: "tomato",
смотри, ты можешь в хелперах написать функции для того чтобы динамически добавлять новое поле с классом  в твой объект. таким образом, когда ты будешь получать данные с сервера - ничего не сломается.

2022-02-28 12:06 UTC, askomarov commented on src/frontend/src/common/helpers.js
> +    foundation: "tomato",
Логики не вижу, классы придуманы, имена придуманы, даже если будет новое тесто или соус все равно руками вводите это новое слово класс

2022-02-28 12:07 UTC, askomarov commented on src/frontend/src/common/helpers.js
> +    foundation: "tomato",
@pisarevamarina

2022-03-25 19:53 UTC, merged