поправил подсчет цены,
htmlacademy-vue/1422707-pizza-1 pull request #3
Opened 2022-03-28 17:38 UTC by askomarov

настроил router - как понял так и настроил

2022-03-28 17:46 UTC, pisarevamarina commented on src/frontend/src/views/Index.vue
> +      console.log(dough);
консоли лучше сразу убирать после дебагинга)

2022-03-28 18:21 UTC, pisarevamarina requested changes
Артем, отлично, с маршрутизацией разобрался, роуминг подключен и работает корректно! нужно доработать функционал связанный с корзиной (отображать итоговую сумму заказа), так же сломалось изменение вида пиццы при переключении видов теста (тонкое/толстое) + мелкие комментарии, чтобы улучшить общий вид кода)  P.S. напишу в личку по поводу хелперов

2022-03-28 18:21 UTC, pisarevamarina commented on src/frontend/src/views/Index.vue
> +      console.log(this.pizzas.dough);
и тут)

2022-03-28 18:21 UTC, pisarevamarina commented on src/frontend/src/layouts/AppLayoutDefaultHeader.vue
> +      <router-link :to="{ name: 'Cart' }" href="cart.html"> 0 ₽ </router-link>
href не требуется, его роль играет  to

2022-03-28 18:21 UTC, pisarevamarina commented on src/frontend/src/layouts/AppLayoutDefaultHeader.vue
> +      <a href="#" class="header__login"><span>Войти</span></a>
router-link уже знаем)

2022-03-28 18:21 UTC, pisarevamarina commented on src/frontend/src/layouts/AppLayoutDefaultHeader.vue
> +      <router-link :to="{ name: 'Cart' }" href="cart.html"> 0 ₽ </router-link>
сюда уже должна попадать  итоговая стоимость заказа при нажатии на "готовьте"

2022-03-28 18:21 UTC, pisarevamarina commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
>              :checked="item.class === selectedDough.name"
может по айдишнику будем проверять?

2022-04-01 17:57 UTC, askomarov commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
>              :checked="item.class === selectedDough.name"
c id только если так   :checked="item.id === 1"

2022-04-01 18:37 UTC, askomarov commented on src/frontend/src/layouts/AppLayoutDefaultHeader.vue
> +      <router-link :to="{ name: 'Cart' }" href="cart.html"> 0 ₽ </router-link>
не смог, с помощью эмита

2022-04-03 06:02 UTC, merged