Module4 task1
htmlacademy-vue/1422707-pizza-1 pull request #4
Opened 2022-06-15 17:51 UTC by askomarov

2022-06-15 21:36 UTC, enotke requested changes

2022-06-15 21:36 UTC, enotke commented on src/frontend/src/components/VIngredient.vue
>        ></VIngredientCounter>
https://up.htmlacademy.ru/vue/1/criteries#b14

2022-06-15 21:36 UTC, enotke commented on src/frontend/src/components/VIngredient.vue
> +        :modClass="modClass"
можно написать просто class="counter--orange ingredients__counter"

2022-06-15 21:36 UTC, enotke commented on src/frontend/src/components/VIngredient.vue
>        ingredient: this.item.class,
Лучше перенести это в computed

2022-06-15 21:36 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizza.vue
> +    isBtnActive() {
лучше в computed перенести

2022-06-15 21:36 UTC, enotke commented on src/frontend/src/router/router.js
> +    meta: { layout: "AppLayoutDefault" },
А зачем везде дефолтный layout указывать? Он же и так должен по дефолту подключаться

2022-06-15 21:36 UTC, enotke commented on src/frontend/src/store/modules/builder.store.js
> +      state.orderedPizza.dough = state.doughList[id - 1];
Лучше искать элементы в списке по ID, а не опираться на ключи массива. То что у тебя ID элементов идут по порядку и начитаются с единицы просто совпадение. ID - это произвольное число

2022-06-16 17:09 UTC, askomarov commented on src/frontend/src/components/VIngredient.vue
> +        :modClass="modClass"
вот это я молодец)) сейчас даже смешно от того как у меня это было написано)

2022-06-16 23:26 UTC, merged

2022-06-17 06:04 UTC, enotke commented on src/frontend/src/components/VIngredient.vue
>        <VIngredientCounter
Что-то ты в VIngredientCounter нагородил. Там не должно быть внутреннего состояния. Тогда не придется вешать watch на значение и постоянно его синхронизировать с внутренним состоянием компонента

2022-06-17 17:37 UTC, askomarov commented on src/frontend/src/components/VIngredient.vue
>        <VIngredientCounter
@enotke спасибо! поправил) раньше мне еще не говорили что так плохо)